apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  username: aGFyaXNobjY2MkBnbWFpbC5jb20=
  password: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-pod
  template:
    metadata:
      labels:
        app: secret-pod
    spec:
      containers:
        - name: secret-container
          image: busybox:1.28
          command: ["sh", "-c", "echo $USERNAME $PASSWORD && sleep 3600"]
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
# kubectl exec -it secret-pod -- /bin/sh
# echo $USERNAME
# echo $PASSWORD

# echo -n "password" | base64

# echo "cGFzc3dvcmQ=" | base64 --decode

